dist: xenial
language: python
python:
  - '3.7'

services:
  - docker

# decrypt the deploy key
before_install:
  - openssl aes-256-cbc -k "$ENCRYPTION_KEY" -in deploy_key.enc -out deploy_key -d

# command to install dependencies
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'

# command to run tests
script:
  - coverage run -m unittest discover tests/ -v
  - codecov
  - ls

# TODO only deploy if this is from master
deploy:
  provider: script
  skip_cleanup: true
  script:
    - bash docker_push
    - chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i deploy_key pontus@api.myfoodplan.app ./deploy_foodplanner.sh
  on:
    all_branches: true
