dist: xenial
language: python
python:
  - '3.7'

services:
  - docker

# command to install dependencies
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'

# command to run tests
script:
  - coverage run -m unittest discover tests/ -v
  - codecov

# TODO only deploy if this is from master
deploy:
  provider: script
  skip_cleanup: true
  script:
    - './docker_push'
  on:
    all_branches: true
