dist: xenial
language: python
python:
  - '3.7'
# command to install dependencies
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'
# command to run tests
script:
  - coverage run -m unittest discover tests/ -v
  - codecov
