#!/bin/bash
echo "Logging in to docker hub"
echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
echo "Building docker image"
docker build . -t pontusw/foodplanner-api:latest
echo "Pushing docker image"
docker push pontusw/foodplanner-api:latest