version: '3'

services:
  frontend:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "8000:5000"
    links:
      - postgres:dbserver
    volumes:
      - ./app:/home/foodlist/app

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Rand0MPazsw0rd
      POSTGRES_DB: foodlist
    ports:
      - "5432:5432"