"""empty message

Revision ID: 2292374f79e9
Revises: 7a68d05ace01
Create Date: 2019-07-01 09:58:51.175287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2292374f79e9'
down_revision = '7a68d05ace01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodcategories', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'foodcategories', 'list', ['list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foodcategories', type_='foreignkey')
    op.drop_column('foodcategories', 'list_id')
    # ### end Alembic commands ###
