"""empty message

Revision ID: 7cb45394f373
Revises: 408c99de9996
Create Date: 2019-06-30 23:11:56.730640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb45394f373'
down_revision = '408c99de9996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'name')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('day', 'day',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('day', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'day', ['list_id', 'day'])
    op.add_column('entry', sa.Column('meal_id', sa.Integer(), nullable=True))
    op.alter_column('entry', 'day_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entry', 'value',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.create_unique_constraint(None, 'entry', ['day_id', 'meal_id'])
    op.drop_constraint('entry_day_id_fkey', 'entry', type_='foreignkey')
    op.create_foreign_key(None, 'entry', 'meals', ['meal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'entry', 'day', ['day_id'], ['id'], ondelete='CASCADE')
    op.drop_column('entry', 'key')
    op.alter_column('list', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_column('list', 'entries_per_day')
    op.drop_column('list', 'entry_names')
    op.alter_column('listpermission', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listpermission', 'permission_level',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('listpermission', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listpermission', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listpermission', 'permission_level',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('listpermission', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('list', sa.Column('entry_names', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('list', sa.Column('entries_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('list', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.add_column('entry', sa.Column('key', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.create_foreign_key('entry_day_id_fkey', 'entry', 'day', ['day_id'], ['id'])
    op.drop_constraint(None, 'entry', type_='unique')
    op.alter_column('entry', 'value',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('entry', 'day_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('entry', 'meal_id')
    op.drop_constraint(None, 'day', type_='unique')
    op.alter_column('day', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('day', 'day',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_table('ingredients')
    op.drop_table('meals')
    op.drop_table('foods')
    # ### end Alembic commands ###
