"""empty message

Revision ID: 910108f8e7f7
Revises: 7cb45394f373
Create Date: 2019-06-30 23:19:51.675080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910108f8e7f7'
down_revision = '7cb45394f373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listpermission_list_id_fkey', 'listpermission', type_='foreignkey')
    op.drop_constraint('listpermission_user_id_fkey', 'listpermission', type_='foreignkey')
    op.create_foreign_key(None, 'listpermission', 'list', ['list_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'listpermission', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listpermission', type_='foreignkey')
    op.drop_constraint(None, 'listpermission', type_='foreignkey')
    op.create_foreign_key('listpermission_user_id_fkey', 'listpermission', 'user', ['user_id'], ['id'])
    op.create_foreign_key('listpermission_list_id_fkey', 'listpermission', 'list', ['list_id'], ['id'])
    # ### end Alembic commands ###
