"""empty message

Revision ID: c2fc303e32ef
Revises: ce862cfef3d0
Create Date: 2019-06-30 23:50:53.834234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fc303e32ef'
down_revision = 'ce862cfef3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
